### ISSUE TITLE
Live Preview not working

### ISSUE THREAD

**Issue by skramstad** [buzzingpixel/craft-static#4]
Hi.

When I enable this plugin, live preview does not work. I see my dashboard instead.

Craft 3.0.26

**Comment by tjdraper** [comment]
I'm not quite sure how that's possible based solely on only this plugin. I have to believe there are other factors at play. Are you able to provide more details about your setup?

**Comment by skramstad** [comment]
I'm not sure either. I dont know if you can check if admin or not and then skip the static version showing up. I've seen other cache plugins do this, but not sure how they do it.

My setup var very generic and just latest craft cms with your plugin aktivated.

**Comment by tjdraper** [comment]
So the only thing this plugin does is provide a service and Twig extension to save the output of a template to a file on disk. I'm not sure how it could cause the problem you're describing.
